### ISSUE TITLE
Use environment.yml

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/recode-perceptions#24]
Use this instead of the requirements.txt
```yaml
name: recode
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - torchaudio==0.9.1
  - cudatoolkit=10.2
  - pytorch==1.9.1
  - torchvision==0.10.1
  - wandb
  - tqdm
  - matplotlib
  - pandas
```

And also change the `environment.sh` folder to be simply:
```sh
module load anaconda3/personal
module load cuda/10.2
conda env create -f environment.yml
```
